### PR TITLE
Change render_app not to break when a record is missing

### PR DESCRIPTION
**Pull request by martin3000**
The records in the app need not necessarily be consecutive. There can be gaps. The sequence can be 2,2 - 2,3 - 3,4

### CODE REVIEW

**Comment by russss** [comment]
Looks like there are some linting errors here but otherwise it looks good!

**Comment by martin3000** [comment]
I cannot see what causes the exit code 1 !?

**Comment by russss** [comment]
This block of code indented too much:

https://github.com/russss/python-emv/blob/fedb7d6ff9f39786cd3f0b5d58717b3eed34b81d/emv/command/client.py#L114-L122

**Comment by martin3000** [comment]
How can I see what the problem is? The log does not explain the failure.

**Comment by martin3000** [comment]
Sorry I give up. I do not understand what is happening and I cannot do anything more.
Shall I close the pull request?

**Comment by russss** [comment]
I've fixed it for you - it's easiest if you have Black running locally to see what's going on. It's a bit pedantic about formatting.

**Pull request merged**
